---
# Configure variables for role
- include_tasks: variables.yml

# Pre-setup tasks and checks
- name: Fail if consul_encrypt_string is empty
  fail:
    msg: "The variable 'consul_encrypt_string' is empty"
  when: consul_encrypt_string | length == 0

- name: Check to see if Consul exists on the system
  stat:
    path: /usr/local/bin/consul
  register: consul_upgrade

# Configure Consul
- include_tasks: install.yml
- include_tasks: config.yml

# Optional tasks to configure consul-template
- include_tasks: ctpl.yml
  when: consul_ctpl_enabled

- name: Ensure Consul is started and enabled on boot
  service:
    name: consul
    state: started
    enabled: true
  ignore_errors: true

- name: Run systemctl status consul
  command: 'systemctl status consul'
  ignore_errors: true

- name: Run journalctl for consul
  command: 'journalctl -u consul'
  ignore_errors: true
...
