---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: consul-server
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - server
  - name: consul-client
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - client
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        consul_encrypt_string: 'NlJcajOKaGiitpFQBLA7BlDlu25PSm3AkRUYAI2MixE='
        consul_retry_join:
          - "[[ hostvars['consul-server']['ansible_default_ipv4']['address'] ]]"
      server:
        consul_server: true
