---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: consul-server
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - server
  - name: consul-client
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - client
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        consul_encrypt_string: 'encryptme123='
        consul_retry_join:
          - consul-server
      server:
        consul_server: true
verifier:
  name: ansible
