---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - server
  - name: client
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - client
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        consul_encrypt_string: 'encryptme123='
        consul_retry_join:
          - "{{ hostvars['server']['ansible_default_ipv4']['address'] }}"
      server:
        consul_server: true
