on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@master
